config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'acercade', to: 'pages#acercade'
  get 'deportes', to: 'pages#deportes'
  get 'sociales', to: 'pages#sociales'
  get 'clasificados', to: 'pages#clasificados'
  get 'otaku', to: 'pages#otaku'
  get 'registrarse', to: 'users#new'
  get 'ingresar', to: 'session#nueva'
  post 'ingresar', to: 'session#crear'
  delete 'cerrarsesion', to: 'session#destruir'
  get 'buscar', to: 'pages#buscar'
  post 'password/forgot', to: 'password#forgot'
  post 'password/reset', to: 'password#reset'
  resources :articulos
  resources :sessions
  resources :users, except: [:new]
  resources :image_elements
  resources :avatar_elements
  resources :password_resets
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def nueva
  end

  def crear
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
        flash[:notice] = "Ingresaste Exitosamente"
        redirect_to user
    else
        flash.now[:alert] = "Algo Salio Mal"
        render 'nueva'
    end
  end

  def destruir
    cookies.delete(:auth_token)
    flash[:notice] = "Cerraste Sesion"
    redirect_to root_path
  end


end

app/views/session/nueva.html.erb
<h1 class="text-center mt-4">Ingresa A Tu Cuenta</h1>
<div class= "container" id="home-container">
<%= form_with(scope: :session, url: ingresar_path, local: true)  do |f| %>

  <div class="form-group row">
    <%= f.label :email, class: "col-form-label" %><br/>
    <%= f.email_field :email, class: "form-control", placeholder: "Aqui Va Tu E-mail" %>
  </div>
  <div class="form-group row">
    <%= f.label :password, class: "col-form-label" %><br/>
    <%= f.password_field :password, class: "form-control", placeholder: "Aqui Va Tu Contrasena" %>
  </div>
    <p><%= link_to "Olvidaste tu contrasena?", new_password_reset_path %></p>
  <div class="field">
  <%= check_box_tag :remember_me, 1, params[:remember_me] %>
  <%= label_tag :recuerda_session %>
  </div>

  <div class="form-group row justify-content-center">
    <%= f.submit "ingresar", class: "btn btn-outline-light btn-lg" %>
  </div>

</div>
<% end %>