config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'acercade', to: 'pages#acercade'
  get 'deportes', to: 'pages#deportes'
  get 'sociales', to: 'pages#sociales'
  get 'clasificados', to: 'pages#clasificados'
  get 'otaku', to: 'pages#otaku'
  get 'registrarse', to: 'users#new'
  get 'ingresar', to: 'session#nueva'
  post 'ingresar', to: 'session#crear'
  delete 'cerrarsesion', to: 'session#destruir'
  get 'buscar', to: 'pages#buscar'
  post 'password/forgot', to: 'password#forgot'
  post 'password/reset', to: 'password#reset'
  resources :articulos
  resources :sessions
  resources :users, except: [:new]
  resources :image_elements
  resources :avatar_elements
  resources :password_resets
end

app/views/layouts/_carousel.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">

    <div class="carousel-item active">
      <% @articulo.order(id: :asc).limit(1).each do |articulo| %>
      <%= image_tag(url_for(articulo.image_elements), width: "100%", height: "100%") %>
      <% end %>
      <div class="carousel-caption d-none d-md-block">
        <% @articulo.order(id: :asc).limit(1).each do |articulo| %>
        <h5><%= articulo.titulo %></h5>
        <p><%= articulo.cuerpo %></p>
        <% end %>
      </div>
    </div>
    <div class="carousel-item">
      <% @articulo.order(id: :desc).limit(1).each do |articulo| %>
      <%= image_tag(url_for(articulo.image_elements), width: "100%", height: "100%") %>
      <% end %>
      <div class="carousel-caption d-none d-md-block">
        <% @articulo.order(id: :desc).limit(1).each do |articulo| %>
        <h5><%= articulo.titulo %></h5>
        <p><%= articulo.cuerpo %></p>
        <% end %>
      </div>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright 2020 &copy; El Aguila y La Serpiente</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<%= link_to "El Aguila y La Serpiente", root_path, class: "navbar-brand" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Acerca De", acercade_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Deportes", deportes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sociales", sociales_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Clasificados", clasificados_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Rincon Otaku", otaku_path, class: "nav-link" %>
      </li>
      <% if sesion_iniciada? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if usuario_ensesion.admin? %> <%= usuario_ensesion.nombredeusuario %>
          </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Ve Tu Perfil", user_path(usuario_ensesion), class: "dropdown-item" %>
              <%= link_to "Edita Tu Perfil", edit_user_path(usuario_ensesion), class: "dropdown-item" %>
              <%= link_to "Borra Tu Perfil", user_path(usuario_ensesion), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Estas Seguro?" } %>
            </div>
        </li>

        <li class="nav-item">
          <%= link_to "Cerrar Sesion", cerrarsesion_path, class: "nav-link", method: :delete %>
        </li>

        <% else %>
        <li class="nav-item">
          <%= link_to "Iniciar Sesion", ingresar_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Registrarse", registrarse_path, class: "nav-link" %>
        </li>
      <% end %>
      <% if sesion_iniciada? && usuario_ensesion.admin? %>
        <li class="nav-item">
          <%= link_to "Crear Articulo", new_articulo_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <%= form_tag(buscar_path, :method => "get",
    class: 'navbar-form navbar-left') do %>
  <div class="input-group">
    <%= search_field_tag :search, params[:search], placeholder: "ingresa tu busqueda", class: "form-control" %>
    <div class="input-group-btn">
      <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%> <%= link_to "", buscar_path, class: "nav-link" %></button>
    </div>
  </div>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EAYLS4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>