config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'acercade', to: 'pages#acercade'
  get 'deportes', to: 'pages#deportes'
  get 'sociales', to: 'pages#sociales'
  get 'clasificados', to: 'pages#clasificados'
  get 'otaku', to: 'pages#otaku'
  get 'registrarse', to: 'users#new'
  get 'ingresar', to: 'session#nueva'
  post 'ingresar', to: 'session#crear'
  delete 'cerrarsesion', to: 'session#destruir'
  get 'buscar', to: 'pages#buscar'
  post 'password/forgot', to: 'password#forgot'
  post 'password/reset', to: 'password#reset'
  resources :articulos
  resources :sessions
  resources :users, except: [:new]
  resources :image_elements
  resources :avatar_elements
  resources :password_resets
end

app/models/articulo.rb
class Articulo < ApplicationRecord
    belongs_to :user
    validates :titulo, presence: true, length: {minimum: 6, maximum: 100}
    validates :cuerpo, presence: true, length: {minimum: 10, maximum: 30000}
    has_one_attached :image_elements
    before_save {self.categoria = categoria.downcase}

    def self.search(search)
        where("lower(articulo.titulo) LIKE :search", search: "%#{search.downcase}%").uniq
    end
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
    before_action :set_articulo, only: [:show, :edit, :update, :destroy]
    before_action :requerir_usuario, except: [:index, :show]
    before_action :requerir_mismo_usuario, only: [:edit, :update, :destroy]

    def show

    end

    def index
      if sesion_iniciada? && usuario_ensesion.admin?
        @articulo = Articulo.all.order("created_at DESC").paginate(page: params[:page], per_page: 10)
      else
        redirect_to root_path
      end
    end

    def new
      if sesion_iniciada? && usuario_ensesion.admin?
        @articulo = Articulo.new
      else
        redirect_to root_path
      end
    end

    def edit

    end

    def create
      @articulo = Articulo.new(params.require(:articulo).permit(:titulo, :cuerpo, :categoria, :image_elements))
      @articulo.user = usuario_ensesion
      if @articulo.save
        flash[:notice] = "Articulo fue creado con exito"
        redirect_to articulos_path(@articulo)
      else
        render 'new'
      end
    end

    def update
      if @articulo.update(params.require(:articulo).permit(:titulo, :cuerpo, :categoria, :image_elements))
        flash[:notice] = "Articulo Editado Con Exito"
        redirect_to @articulo
      else
        render 'edit'
      end
    end

    def destroy
      @articulo.destroy
      redirect_to articulos_path
    end

    private

    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    def requerir_mismo_usuario
      if usuario_ensesion != @articulo.user && !usuario_ensesion.admin?
        flash[:alert] = "Solo Administradores Pueden Modificar Articulos"
        redirect_to @articulo
      end
    end

end

app/views/articulos/_articulos.html.erb
<div class="container">
  <% @articulo.each do |articulo| %>
  <div class="card mb-3 shadow mb-5 bg-white rounded" style="max-width">
    <div class="row no-gutters">
      <div class="col-md-4">
        <h1 class = "text-align-left"><%= image_tag(url_for(articulo.image_elements), :size => "300x200") %></h1>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title text-center"><%= articulo.titulo %></h5>
          <p class="card-text text-center"><%= articulo.cuerpo.truncate(100) %></p>
          <p class="card-text text-center"><%= articulo.user.nombredeusuario %></p>
          <p class="card-text text-center"><small class="text-muted">Creado hace <%= time_ago_in_words(articulo.updated_at) %></small></p>
          <h6 class= "text-center"><%= link_to "Leer mas", articulo_path(articulo), class: "btn btn-success btn-lg " %></h6>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/articulos/_form.html.erb
<%= render 'shared/errors', obj: @articulo %>

<%= form_with(model: @articulo, local: true)  do |f| %>
  <div class="form-group row">
    <%= f.label :titulo, class: "col-form-label" %><br/>
    <%= f.text_field :titulo, class: "form-control" %>
  </div>
  <div class="form-group row">
    <%= f.label :cuerpo, class: "col-form-label" %><br/>
    <%= f.text_area :cuerpo, rows: 15, class: "form-control" %>
  </div>
  <div class="form-group row">
  <%= f.label :categoria, class: "col-form-label" %><br/>
  <%= f.text_area :categoria, rows: 2, class: "form-control" %>
  </div>
  <div class="form-group row">
    <%= f.label "Foto De Articulo" %>
    <%= f.file_field :image_elements %><br/>
  </div>
  <div class="form-group row justify-content-center">
    <%= f.submit class: "btn btn-outline-light btn-lg" %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<div class= "container" id="home-container">
    <h1>Edita El Articulo</h1>
    <h2><small>No Te Preocupes Todos Cometemos Errores</small></h2>

<%= render 'form' %>

<p>
  <%= link_to 'Cancelar Cambio', articulos_path %>
</p>
</div>

app/views/articulos/index.html.erb
<div class= "container text-center" id="home-container">
<table class="text-center">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Creador</th>
      <th>Categoria</th>
    </tr>
  </thead>

  <%= will_paginate @articulo %>
  <tbody>
    <% @articulo.each do |articulo| %>
      <tr>
        <td class= "text-left"><%= articulo.titulo %></td>
        <td class= "text-left"><%= articulo.user.nombredeusuario %></td>
        <td class= "text-left"><%= articulo.categoria %></td>
        <td><%= link_to 'Mostrar', articulo_path(articulo) %></td>
        <td><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
        <td><%= link_to 'Eliminar', articulo_path(articulo), method: :delete, data: { confirm: "Estas Seguro De Querer Eliminar?" } %></td>
      </tr>
      <% end %>
  </tbody>

</table>
<p class= "text-left">
<%= link_to 'Nuevo Articulo', new_articulo_path %>
</p>
  <%= will_paginate @articulo %>
</div>

app/views/articulos/new.html.erb
<div class= "container" id="show-container">
  <h1 class = "text-center">Crea Un Articulo Nuevo</h1>

  <%= render 'form' %>

  <button type="button" class="btn btn-outline-primary">
    <%= link_to 'Regresar Al Listado', articulos_path %>
  </button>
</div>

app/views/articulos/show.html.erb
<div class= "container" id="show-container">
  <h1 class="text-center mt-4"><%= @articulo.titulo %></h1>
    <div class="container">
      <div class="card mb-3 shadow mb-5 bg-white rounded" style="max-width">
        <div class="row no-gutters">
          <div class="col-md-4">
             <% if @articulo.image_elements %>
            <h1 class = "text-center mt-4"><%= image_tag(url_for(@articulo.image_elements),  :size => "700x500") %></h1>
            <% else %>
            <% end %>
          </div>
          <div class="col-md-12">
            <div class="card-body">
              <h5 class="card-title text-align-right"><%= @articulo.titulo %></h5>
              <div class="card-text text-align-right"><%= simple_format(@articulo.cuerpo) %></div>
              <div class="card-text text-align-right"><small class="text-muted">Creado hace <%= time_ago_in_words(@articulo.updated_at) %></small></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <button type="button" class="btn btn-outline-primary">
    <%= link_to 'Regresar A Casa', root_path %>
  </button>
</dv>